nhsuk/nhsuk.service-manual.prototype-kit.docs

README.md

Initial commit just to make the README a bit clearer that this repo is intended to be for the guidance for the prototype kit rather than the kit itself.

Update README to distinguish guidance from the prototype kit itself

---

app/routes.js
app/views/install/download-zip.html
app/views/install/download.html
app/views/layout.html
package.json

Added new property `prototypeKitVersion` to `package.json`.
Also set this repo to v0.1.0

Fix link to zip file

---

app/views/how-tos/components.html
app/views/how-tos/passing-data-page.html
app/views/install/advanced.html
app/views/install/node.html
app/views/templates/confirmation-page.html
app/views/templates/google.html

Spotted by running an HTML checker.

Minor HTML bug fixes

---

app/views/how-tos/switching-from-govuk-prototype-kit.html

Hope this isn’t too fussy. Have consistent indenting can be helpful for spotting HTML typos (eg I spotted a missing `</p>`) and lets some code editors do 'folding' where you can collapse different sections.

Tweaks to the indenting of html and Nunjucks

---

app/views/install/index.html

Added information to the install page about switching from the GOV.UK prototype kit

---

.github/workflows/tests.yml
.gitignore

This adds an explicit test to check that the build actually works.

Add test build

---

.github/workflows/tests.yml
package.json

May as well run these, as they're there.

Run Jest tests from GitHub Workflow

---

app.js

Set strict transport security header

---

app/views/how-tos/build-basic-prototype/_BASE.njk
app/views/how-tos/build-basic-prototype/link-pages-together.html

| Before |  After |
| --- | ---- |
| <img width="666" alt="page with start.html" src="https://github.com/user-attachments/assets/8ca5ee92-c0f4-412e-b9b7-4407b3e69d12"> | <img width="464" alt="page with start-page.html" src="https://github.com/user-attachments/assets/35815400-2170-4a4b-926e-4f36e3fff0e9"> |

Fix link mentioning start page to be correct URL and add check correct links

---

app/views/how-tos/build-basic-prototype/use-components-2.html

| Before | After | 
| --- | --- |
| <img width="688" alt="old page with magical-powers.html" src="https://github.com/user-attachments/assets/d7926359-324b-40b8-b0db-45720968a8f6"> | <img width="503" alt="New page with details.html" src="https://github.com/user-attachments/assets/3160902e-55ca-4de6-8db0-c3d26f3a2f5f"> |

fixed page url to be correct

---

app/views/how-tos/build-basic-prototype/create-pages.html

| --- | ----- |
|  <img width="678" alt="text with H1 tag" src="https://github.com/user-attachments/assets/60f560a2-bd91-4d8a-976f-0d8900c50994">  |  <img width="449" alt="text changed to legend and text" src="https://github.com/user-attachments/assets/754e79b6-f849-4b01-bcc3-08124774f4ed"> |

Fixed mistake from using question-page 

---

app/views/how-tos/build-basic-prototype/show-users-answers.html

There was a line from the old prototype kit that is no longer needed.

Removed unnecessary line

---

README.md

Added note for internal use about quotes:
> #### quotation marks
>
> Use straight quotes only (not smart or curly quotes). More detail is in the <a href="https://service-manual.nhs.uk/content/formatting-and-punctuation#quotation-marks">Formatting and punctuation</a> part of the Digital service manual content guide.

Update README to have details about quotes

---

app/views/whats-new/updates.html

Add notes for v5.2 release to the updates page on the site

Added v5.2 basic notes

---

app/views/how-tos/publish-your-prototype-online.html

`NODE-ENV` should be `NODE_ENV` as per the code in `app.js` and `authentication.js`

use the correct variable name for NODE_ENV

---

.devcontainer/devcontainer.json

Fixes #187
Mainly based on the GitHub Codespaces config added to the prototype kit itself.

Add codespaces config

---

app/assets/sass/prism.scss

Ensure they are all above 4:5 contrast.

Fix code highlight colour contrast

---

app/views/how-tos/git.html

Updating the '[Setting up Git](https://prototype-kit.service-manual.nhs.uk/how-tos/git)' guidance with 'how to check if you already have Git installed'. 
(Issue https://github.com/nhsuk/nhsuk.service-manual.prototype-kit.docs/issues/209)
| -------|-------|
| ![image](https://github.com/user-attachments/assets/cad0ad6e-81c2-4aee-a8e5-2b03b4ce404a) | ![image](https://github.com/user-attachments/assets/6140f5e7-9d21-4b4d-990b-77a774552c21) |

Update guidance on Git

---

gulpfile.js

Remove reference to docs folder

---

app/views/examples/passing-data/clear-data-success.html
app/views/examples/passing-data/clear-data.html
app/views/examples/passing-data/passing-data-confirmation.html
app/views/examples/passing-data/passing-data-question-conditions.html
app/views/examples/passing-data/passing-data-question-contact.html
app/views/examples/passing-data/passing-data-question-name.html
app/views/how-tos/passing-data-page.html
app/views/whats-new/updates.html
package.json

This updates the documentation website for the NHS prototype kit for version 6.0.0.

Updates for 6.0.0

---

app/assets/sass/nhsuk.scss

Remove /all suffix

---

app/views/how-tos/github/_BASE.njk

Thanks to @paulmsmith for spotting and reporting.

Fix links in guide

---

gulpfile.js
package-lock.json
package.json

This is faster as it uses a native executable: https://www.npmjs.com/package/sass-embedded

Switch to sass-embedded

---

app/views/layout.html

These were accidentally dropped (by me) in #259.

Add images for social media sharing back in
