package.json

This lets you do `npm run lint:js:fix` to more easily run the JavaScript code style checks in auto-fix mode.

Add lint:js:fix script

---

app/views/layout.html

Using the macros rather than the HTML is more future-proof for any upcoming component changes.
There’s not currently a way to put a paragraph into footer, but I’m not sure the full paragraph about cookies is needed? Have made it a plain link instead.
Also removed the redundant 'Home' link.
| ------ | ------|
| <img width="1206" alt="footer-before" src="https://github.com/user-attachments/assets/0b15b98d-d516-4c76-a39d-bb39589a5c66"> | <img width="1173" alt="footer-after" src="https://github.com/user-attachments/assets/a76a39da-3b35-4e81-ba57-f343ebcea5d5"> |

Switch to using footer macro

---

app/views/index.html
app/views/layout.html

This is more future-proof, especially with upcoming changes to the header.
Also fixes a bug where the service name wasn't appearing in the header on the homepage - not sure if that was deliberate or not but feels wrong?
Otherwise there’s no changes.
| -------|-------|
| <img width="1210" alt="Prototype Kit website with just the NHS logo in the header" src="https://github.com/user-attachments/assets/414a2e8b-8302-474f-adc0-8c83d99e0d9a"> | <img width="1210" alt="Prototype Kit website with 'Prototype Kit' next to NHS logo in the header" src="https://github.com/user-attachments/assets/8fa26375-760d-4274-9a43-202102903b0c"> |

Switch to using the header macro

---

app/views/how-tos/switching-from-govuk-prototype-kit.html

removed node versions as not needed, added details about heroku password, merged some points
| Old version  | New version |
| ------------- | ------------- |
| ![Old version of 'switching from the GOV.UK Prototype Kit' page](https://github.com/user-attachments/assets/f474d99a-f1c4-4010-9f27-fab180d35854) | ![New version of 'switching from the GOV.UK Prototype Kit' page with new section on passwords and other minor tweaks](https://github.com/user-attachments/assets/a2d77af6-f2a8-4ca2-98dd-ec4dffd0236d)  |

Tweaks to 'switching from the GOV.UK Prototype Kit' page

---

app/views/how-tos/switching-from-govuk-prototype-kit.html
app/views/install/check-it-works.html
app/views/install/download.html
app/views/install/mac/check-it-works.html
app/views/install/mac/download.html
app/views/install/mac/node.html
app/views/install/mac/open.html
app/views/install/mac/run.html
app/views/install/mac/setup.html
app/views/install/mac/terminal.html
app/views/install/mac/text-editor.html
app/views/install/node.html
app/views/install/open.html
app/views/install/run.html
app/views/install/setup.html
app/views/install/terminal.html
app/views/install/text-editor.html
app/views/install/windows/check-it-works.html
app/views/install/windows/download.html
app/views/install/windows/git-bash.html
app/views/install/windows/node.html
app/views/install/windows/open.html
app/views/install/windows/run.html
app/views/install/windows/setup.html
app/views/install/windows/terminal.html
app/views/install/windows/text-editor.html

Added:
- breadcrumb at top of pages of operating-model specific steps to link back to start of install guide https://prototype-kit.service-manual.nhs.uk/install/simple . Not added to system choice as this is a switcher page and has a link at the bottom to get back to the install home
- variable on steps to show operation system (windows or mac) set on the child pages with a nunjucks variable (this is used rather than the data from the radio buttons in case someone comes to the pages directly as choosing your operating system is only for triaging to the right pages). System added after steps to be reassurance but less repetitive than being at the beginning (Mac: Step 1 of 8) 
The advanced guide is not changed as it is one level down from the get started guide and a single page so does not …

Install guide: add signposting about chosen operation system and breadcrumb to guide start

---

app/views/install/check-it-works.html

Change guide to go from make pages to start of tutorial.
> <p><a href="/how-tos/build-basic-prototype/index">Build a basic prototype</a> or view other <a href="/how-tos/index">how to guides</a>.</p>
This is done in the main file that cascades to both mac and windows versions.
| ---- | ---- |
|  <img width="269" alt="old version linking to make pages" src="https://github.com/user-attachments/assets/dc418411-9fb5-41cb-8432-182b1c54b1d9"> | <img width="252" alt="new version linking to both start of tutorial and how to guides" src="https://github.com/user-attachments/assets/f217733a-7e93-46f6-b0e0-62f0e1ccbe1d"> |

change link to go to tutorial and how tos

---

app/views/examples/branching/answer-no.html
app/views/examples/branching/answer-yes.html
app/views/examples/branching/index.html
app/views/how-tos/adding-assets.html
app/views/how-tos/branching.html
app/views/how-tos/build-basic-prototype/_BASE.njk
app/views/how-tos/build-basic-prototype/index.html
app/views/how-tos/components.html
app/views/how-tos/git.html
app/views/how-tos/includes/back-button.html
app/views/how-tos/index.html
app/views/how-tos/making-pages.html
app/views/how-tos/passing-data-page.html
app/views/how-tos/publish-your-prototype-online.html
app/views/how-tos/switching-from-govuk-prototype-kit.html
app/views/how-tos/updating-the-kit.html
app/views/install/mac-or-windows.html

Previously the NHS Service Manual used to advise having back links at the bottom of pages.
However following community consultation [this was recently changed](https://github.com/nhsuk/nhsuk-service-manual/pull/2034) to instead suggesting having back links at the top in the `beforeContent` block.
This PR removes a few remaining back links at the bottom of pages. Generally these duplicate either a back link or a breadcrumb at the top and so could just be removed but in a couple of places there was nothing at the top so I’ve moved the back link there instead.

Remove back link from bottom of pages

---

app/views/examples/branching/index.html
app/views/install/mac-or-windows.html

Just a bit of tidying up - no need to use `call fieldset` here as the options can be specified on the `radio` macro directly.
Also switched the macro keys to not be quoted following recent coding style update.

Merge fieldset options into radios macro

---

package-lock.json
package.json

Currently a build is triggered every time `npm install` is run. This can be considered a bit unexpected, and is an unnecessary step when installing the dependencies just to run code style tests.  It also seems to stop the npm cache working.
Instead, this switches the build to happen before starting the app, in the same way that the build happens before running `npm run watch`.

Switch when the 'build' step happens

---

.github/PULL_REQUEST_TEMPLATE.md

This relates to the Prototype Kit itself, rather than the guidance website.

Remove pull request template

---

app/views/how-tos/switching-from-govuk-prototype-kit.html

* removed details that were the same
* rewrote sentence
* added code formatting
Before 
> ## Using routing and session data
> You can define routes to do branching logic or other custom behaviour in the same way as the GOV.UK Prototype Kit.
> You can also add default session data in data/session-data-defaults.js
> Unlike the GOV.UK Prototype Kit, if you save any changes the the routes file, the app will restart and any session data will revert to the default.
After
> ## Using routing and session data
> When you save any changes to `routes.js` file, the app will restart. This will also delete all session data and reset them with any values set in `data/session-data-defaults.js`.

minor changes to switching page

---

app/assets/sass/components/_figure.scss
app/assets/sass/main.scss
app/views/how-tos/build-basic-prototype/index.html
app/views/how-tos/build-basic-prototype/use-components-2.html
app/views/how-tos/build-basic-prototype/use-components.html

This makes a few visual tweaks to images with a caption below them.
Changes:
* remove default margin which is causing the caption and image to be inset
* make the caption text regular font size (19px) for increased readability
* increase margin below the the figure
These styles are configured in a new 'Figure' component to make it easier to maintain.
Thanks @michaelgallagher for spotting.
| ------ | ----- |
| ![Screenshot 2024-11-04 at 10 03 17](https://github.com/user-attachments/assets/ce288f91-66fd-4a66-bd97-138d6c600f4f) | ![Screenshot 2024-11-04 at 09 59 00](https://github.com/user-attachments/assets/8074bc7a-47ef-4d0e-974c-f1d91c82b88e) |

Add Figure component

---

app/views/layout.html

This doesn't need to be set here, as it’s already set in the template. Also doesn't need the word "docs" on the end.

Fix homepage page title

---

README.md

starting point for style guide. 
Things to check:
* all the points really
* anything re formatting. I thought this would be a definition list but the health guide A-Z is headings? 
Fixes #62 
> ### Style guide
>
>We normally use the [NHS content guide](https://service-manual.nhs.uk/content) for terms. But there are some terms that are only used in the guidance for the kit:
>
> ### command line
>
>Lower case. Only use for Windows instructions. Nortmally it will be ‘the command line’.
> 
> #### GOV.UK Prototype Kit, GOV.UK Design System and other GOV.UK products
>
> Title case.
>
> #### NHS, NHS.UK, NHS England
>
> Use ‘NHS.UK’ for products that are for delivery teams and not the public (find out more on the [NHS health writing A-Z](https://service-manual.nhs.uk/content/a-to-z-of-nhs-health- …

Style guide

---

app/views/examples/branching/index.html
app/views/examples/passing-data/clear-data-success.html
app/views/examples/passing-data/clear-data.html
app/views/examples/passing-data/passing-data-check-answers.html
app/views/examples/passing-data/passing-data-confirmation.html
app/views/examples/passing-data/passing-data-question-conditions.html
app/views/examples/passing-data/passing-data-question-contact.html
app/views/examples/passing-data/passing-data-question-name.html
app/views/how-tos/branching.html
app/views/how-tos/build-basic-prototype/_BASE.njk
app/views/how-tos/build-basic-prototype/link-index-page-start-page.html
app/views/how-tos/components.html
app/views/how-tos/git.html
app/views/how-tos/includes/breadcrumb.html
app/views/how-tos/index.html
app/views/how-tos/making-pages.html
app/views/how-tos/passing-data-page.html
app/views/index.html
app/views/install/check-it-works.html

This is a proposal - would be interested to see what others think! Rationale below.
---
This renames the 'How to guides' as simply 'Guides'.
This is because:
* 'How to guides' is an awkward phrase to read, as you. might initially assume the third word is a verb (like "How to code" and then have to re-evaluate it as a noun phrase
* It’s longer than it needs to be, and we might want to have a navigation bar at some point, in which case 'Guides' would be a lot shorter
In addition, some of the guides themselves (which had a mixture of forms) have been renamed to no longer include 'How to'. This also means the link text on the index page now matches the titles when you click through.
They all now start with a verb (although a mix of tenses).
The changes are:
* How to setup Git -> Setting up …

Rename 'How to guides' as 'Guides'

---

app/views/page-templates.html

This fixes the description of where the templates are located within the kit, and adds a clearer description of how to use them.
Also removes the bullets from the lists and tweaks the heading sizes.
Fixes #96

Update page templates page

---

app/views/how-tos/build-basic-prototype/let-user-change-answers.html
app/views/how-tos/build-basic-prototype/show-users-answers.html

This has meant a lot of reworking the page as the original was html rather than nunjucks code. I'm still a bit nervous about explaining how to delete bits of an array but the worked example is there at least. 
| -- | -- |
|  ![original version with HTML examples](https://github.com/user-attachments/assets/ea46dbba-679f-43dd-b43c-9ffaaa5d302d) | ![example with changed code to nunjucks](https://github.com/user-attachments/assets/80813986-4c4d-4c74-afbf-607ff01b8237) |

Show answers page and let users change answers fixed to reflect nunjucks defaults

---

README.md
app/views/how-tos/build-basic-prototype/index.html
app/views/install/requirements.html
app/views/install/text-editor.html

Building on earlier notes to remove mention to Atom and building on it. 
Done in this ticket:
* removed the 1 remaining reference to Atom because it is now not actively in development
* removed 1 mention to Notepad++ for Windows as it was inconsistently recommended between the install guidance and building a basic prototype
* documented and created a consistent way to introduce Visual Studio Code (full name and then shortcut), and describe its benefits (keeping a particular note from the GOV.UK Prototype Kit guidance about accessibility) 
> You'll also need a code editor. Any HTML text editor will do, but we recommend <a href="https://code.visualstudio.com">Visual Studio Code</a> (also known as VS Code). This is because it is free, fairly accessible, and has lots of useful features.
| …

Consolidating guidance for text editors

---

app/assets/sass/main.scss
app/views/layout.html

This adds a "primary nav" with 3 items:
* Get started
* Guides
* Support
"Contribute" could be added when #148 is merged.
I’ve not included "Page templates" as that page feels less valuable longer-term (eg if the NHS website templates get moved to a plugin or something).
Adding the primary nav possibly means that some of the breadcrumbs could be removed or shortened (eg the "Home" breadcrumb link on Support feels a bit odd now?), but the Service Manual website has both, so maybe it’s fine?
There’s no "current section" indicator for now, but we can adopt that when it gets added to the header in the next major release of NHS frontend (hopefully).
Part of #93

Add main nav

---

app/views/how-tos/build-basic-prototype/branching.html
app/views/how-tos/build-basic-prototype/link-pages-together.html
app/views/how-tos/build-basic-prototype/use-components-2.html
app/views/how-tos/build-basic-prototype/use-components.html

Fixed:
Typo on gov template https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/use-components-2
| Before | After | 
| --- | -- |
| <img width="675" alt='Delete {% from "govuk/components/textarea/macro.njk" import govukTextarea %}.' src="https://github.com/user-attachments/assets/d232a10b-eb3f-4c22-a840-ba9781cb230c"> | <img width="695" alt='Delete {% from "textarea/macro.njk" import textarea %}.' src="https://github.com/user-attachments/assets/37fa14bb-3be6-4ac9-9c94-00c126c41f03"> | 
Typo with content page naming on https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/branching
| Before | After | 
| --- | -- |
| <img width="721" alt="Create an ineligible page - Make an ineligible.html page by copying content.html from docs/views/templates to …

Changed the pages based on feedback

---

app/views/how-tos/build-basic-prototype/let-user-change-answers.html

Reported by Dave King:
> I noticed there might be an error in the section 'Show the user's answer in question 2' section on the 'Let the user change their answers' page. The guide says that that you need to add a new line value: data['magical-powers'], but I believe this should be value: data['details'] ? I also think that the example code isn't right as it shows the textarea id as being "example" but it was set in a previous step as "details". Hope this helps :)
Corrected page to be: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/let-user-change-answers
| Before | After | 
| -- | --|
| ![data magical powers](https://github.com/user-attachments/assets/f5449f6a-45f0-47dc-876e-24f2c73d00d0) | ![data details …

Fixed typo (thanks Dave for picking up)

---

app/views/layout.html

Not sure we need this in the footer now that it’s in the header.

Remove contribute link from footer

---

app/views/how-tos/build-basic-prototype/index.html

Fixes duplicate text on this page: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/index

Fixes duplicate text in prototype kit guide intro

---

app/views/how-tos/passing-data-page.html

This updates the [Passing data page to page](https://prototype-kit.service-manual.nhs.uk/how-tos/passing-data-page) guide to add a bit more detail (and fix some issues) without being too overwhelming with more advanced stuff (which could go on a separate guide in future).
Based upon work from @vickytnz in #173 and from the [GOV.UK prototype kit pass data page to page guide](https://prototype-kit.service.gov.uk/docs/pass-data).
Main changes:
* use Nunjucks for all the examples instead of HTML
* slight restructuring of the page
* remove reference to 'Clear data' link for now, as that’s not in the kit yet (see https://github.com/nhsuk/nhsuk-prototype-kit/issues/389)
Part of #172.
➡️ [Preview](https://nhs-prototyp-update-pas-tiulig.herokuapp.com/how-tos/passing-data-page)

Update the 'Passing data page to page' guide

---

app/views/includes/scripts.html

This script adds a hidden checkbox to all forms containing checkboxes, with the same name but a value of `_unchecked`.
This is useful for making sure that the values are always stored in an array, even when a single item is checked, as well as being able to more easily update data when a checkbox is unchecked.
The script was somehow not being referenced, which caused a bug.
Fixes #218

Include auto-store-data script

---

app.js
app/views/examples/passing-data/passing-data-check-answers.html
app/views/examples/passing-data/passing-data-question-conditions.html
app/views/examples/passing-data/passing-data-question-contact.html
app/views/how-tos/build-basic-prototype/_BASE.njk
app/views/how-tos/build-basic-prototype/branching.html
app/views/how-tos/build-basic-prototype/let-user-change-answers.html
app/views/how-tos/build-basic-prototype/show-users-answers.html
app/views/how-tos/build-basic-prototype/use-components.html
app/views/how-tos/passing-data-page.html
lib/utils.js

Since [version 9.2.0 of NHS Frontend](https://github.com/nhsuk/nhsuk-frontend/releases/tag/v9.2.0) there’s now an easier, nicer way of setting the default selected radio option or default checked checkboxes.
Instead of using the `checked()` filter on each `item` within radios and checkboxes, the `value` (for radios) or `values` (for checkbox) of the selected items can be set at the top level of the Nunjucks params.
This pull request updates the guidance to use the newer, easier way of doing this.
The `checked` function/filter is also deleted from the guidance site as it’s no longer needed (but will remain in the kit itself for backwards-compatibility until at least the next major release).

Update guides to use new 'value' option instead of 'checked' filter

---

app/views/examples/passing-data/passing-data-confirmation.html
app/views/template.html

New [Panel component](https://service-manual.nhs.uk/design-system/components/panel) was released in [NHS Frontend 9.3.0](https://github.com/nhsuk/nhsuk-frontend/releases/tag/v9.3.0).
This updates an example in the prototype kit docs to use the new component.
|--------|-------|
| ![previous-confirmation-screen](https://github.com/user-attachments/assets/9f11cbd8-3d6d-4c9f-9a1e-120d505eb8a5) | ![new-confirmation-screen](https://github.com/user-attachments/assets/915aefad-1075-45c4-aec3-f947132de649) |

Update example page to use new Panel component

---

app/views/whats-new/updates.html
package.json

This updates the guidance website to point to the new 5.3.0 release of the prototype kit zip file, and updates the Updates page to describe the new features.

Update to NHS prototype kit 5.3.0

---

app/assets/sass/main.scss
package-lock.json
package.json

This upgrades NHS frontend to 9.4.1 and applies a temporary fix for the button on the homepage.
I’ll switch to using the template now included within NHS frontend as a separate follow-up PR.

Upgrade nhsuk frontend

---

app/assets/sass/components/_figure.scss
app/assets/sass/nhsuk.scss

`nhsuk-typography-responsive` has been deprecated and renamed to `nhsuk-font-size`.

Update nhsuk font size mixin

---

app/views/index.html

Currently it is just "NHS", as it hasn’t been set.

Set page title for homepage

---

app/views/how-tos/branching.html

This updates the existing "How to do branching" page, which contains an incorrect pointer to some example code, to actually displaying the example code itself.
It’s not perfect, but might be a start, and better than what we've got now.

Improve branching guide

---

app/views/how-tos/build-basic-prototype/branching.html
app/views/how-tos/build-basic-prototype/create-pages.html
app/views/page-templates.html

We’ve now removed almost all the example templates from the prototype kit, as there are now pattern pages for them in the NHS Service manual instead, which include additional guidance. 🎉 
One small downside is that the examples in the service manual don’t the layout reference at the top, so the guidance now has to mention adding this to the top of each file:
```njk
{% extends "layout.html" %}
```
Fixes #295

Replace references to examples templates with links to service manual

---

package.json

This updates the link to .zip file download.
I've not added an entry to the [Updates page](https://prototype-kit.service-manual.nhs.uk/whats-new/updates) as we say there that we'll only mention major and minor versions.

Update version number of prototype kit

---

app/views/how-tos/updating-the-kit.html

This makes the guide a bit more future-proof for when there are minor or patch releases of NHS frontend or the prototype kit.

Only specify the major version number in upgrade guide

---

app.js
lib/utils.js

This functionality was inherited from the kit itself, but isn’t needed for the documentation website.

Remove session data defaults

---

app/assets/sass/nhsuk.scss
app/views/templates/nhsuk-coronavirus-hub.html
app/views/templates/nhsuk-healthaz.html
app/views/templates/nhsuk-homepage.html
app/views/templates/nhsuk-layout.html
app/views/templates/nhsuk-livewell.html
app/views/templates/nhsuk-mentalhealth.html
app/views/templates/nhsuk-nhs-services.html
app/views/templates/nhsuk-pregnancy.html
app/views/templates/nhsuk-socialcare.html

This mostly fixes #341 although there are still some more subtle things broken, and  some of the content and design is still out-of-date with the live NHS.UK pages (as the design of those has changed since these templates were made).

Rough fix to NHS.UK templates

---

app/views/how-tos/making-pages.html

This attempts to make improvements by explaining that:
* pages need to start by extending a layout
* sub-folders can be used
* how `index.html` pages are special
It also switches from using `<strong>` to using `<code>` for code and file references.
The 2 images have been removed as they’re out of date, but could be replaced if needed (maybe not though)?

Improve the Making pages guide

---

package-lock.json
package.json

No need to include version number, as we’re using continuous deployment.

Update package metadata
